vich_uploader:
  db_driver: orm

  mappings:
    blog:
      uri_prefix: /images/blog
      upload_destination: '%kernel.project_dir%/public/images/blog'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

